---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - XDG_CONFIG_HOME=/config
      - XDG_DATA_HOME=/config
      - TZ=Europe/London
      - AUTO_UPDATE=false #optional
#      - RUN_OPTS=<run options here> #optional
#    volumes:
#      - /app
#      - <path to blackhole>:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
